name: Pipeline Build

run-name: 'Build Pipeline For ${{github.ref_name}}'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        if: github.ref == 'refs/heads/main'
        run: |
          echo 'Running in main branch'
          mvn clean install

      - name: Build with Maven -- Feature Branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo 'Running in ${{github.ref_name}} branch'
          mvn clean install

  publishing-to-artifact-repositories:

    runs-on: ubuntu-latest
    needs: build
    env:
      REPOSITORY_ID: "maven-snapshots"

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Get Version
        run: echo "POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Print Current Version
        run: echo "Current Version Is - ${{env.POM_VERSION}}"

      - name: Check If Release Version
        if: ${{ !contains(env.POM_VERSION, '-SNAPSHOT') }}
        run: echo "REPOSITORY_ID=maven-release" >> $GITHUB_ENV

      - name: Deploy To Nexus
        run: echo "Deploy artifact to nexus - ${{env.REPOSITORY_ID}}"

      - name: Deploy To OSSRH
        if: ${{ env.REPOSITORY_ID == 'maven-release'}}
        run: echo "Deploy artifacts to OSSRH"